# The .pivot() Method

In [1]:
import pandas as pd

In [25]:
%%html
<style>
    table.dataframe th,table.dataframe td{
        border:1px solid black;
        text-align:left;
        background-color:white;
    }
</style>

In [26]:
sales = pd.read_csv('../salesmen.csv',parse_dates=['Date'])
sales.head()

        Date Salesman  Revenue
0 2016-01-01      Bob     7172
1 2016-01-02      Bob     6362
2 2016-01-03      Bob     5982
3 2016-01-04      Bob     7917
4 2016-01-05      Bob     7837

In [27]:
len(sales)

1830

In [28]:
sales['Salesman'].value_counts()

Ronald    366
Bob       366
Jeb       366
Dave      366
Oscar     366
Name: Salesman, dtype: int64

In [29]:
sales['Salesman'] = sales['Salesman'].astype('category')
sales.head()

        Date Salesman  Revenue
0 2016-01-01      Bob     7172
1 2016-01-02      Bob     6362
2 2016-01-03      Bob     5982
3 2016-01-04      Bob     7917
4 2016-01-05      Bob     7837

In [30]:
sales.pivot(index='Date',columns = 'Salesman',values="Revenue")

Salesman     Bob  Dave   Jeb  Oscar  Ronald
Date
2016-01-01  7172  1864  4430   5250    2639
2016-01-02  6362  8278  8026   8661    4951
2016-01-03  5982  4226  5188   7075    2703
2016-01-04  7917  3868  3144   2524    4258
2016-01-05  7837  2287   938   2793    7771
...          ...   ...   ...    ...     ...
2016-12-27  2045  2843  6666    835    2981
2016-12-28   100  8888  1243   3073    6129
2016-12-29  4115  9490  3498   6424    7662
2016-12-30  2577  3594  8858   7088    2570
2016-12-31  3845  6830  9717   8408    2619

[366 rows x 5 columns]

In [43]:
s = pd.read_csv('../worldstats.csv')
s['country'] = s['country'].astype('category')
s['year']  = s['year'].astype('category')
s.head()

11211

In [44]:
len(s)

11211

In [46]:
s.pivot(index='year',columns='country',values=['Population','GDP'])

         Population                                              \
country Afghanistan    Albania     Algeria  Andorra      Angola
year
1960      8994793.0        NaN  11124892.0      NaN         NaN
1961      9164945.0        NaN  11404859.0      NaN         NaN
1962      9343772.0        NaN  11690152.0      NaN         NaN
1963      9531555.0        NaN  11985130.0      NaN         NaN
1964      9728645.0        NaN  12295973.0      NaN         NaN
1965      9935358.0        NaN  12626953.0      NaN         NaN
1966     10148841.0        NaN  12980269.0      NaN         NaN
1967     10368600.0        NaN  13354197.0      NaN         NaN
1968     10599790.0        NaN  13744383.0      NaN         NaN
1969     10849510.0        NaN  14144437.0      NaN         NaN
1970     11121097.0        NaN  14550033.0  24279.0         NaN
1971     11412821.0        NaN  14960111.0  25560.0         NaN
1972     11716896.0        NaN  15377095.0  26892.0         NaN
1973     12022514.0        NaN  15804428.0  28231.0         NaN
1974     12315553.0        NaN  16247113.0  29514.0         NaN
1975     12582954.0        NaN  16709098.0  30706.0         NaN
1976     12831361.0        NaN  17190236.0  31781.0         NaN
1977     13056499.0        NaN  17690184.0  32769.0         NaN
1978     13222547.0        NaN  18212331.0  33746.0         NaN
1979     13283279.0        NaN  18760761.0  34819.0         NaN
1980     13211412.0        NaN  19337723.0  36063.0         NaN
1981     12996923.0        NaN  19943667.0  37502.0         NaN
1982            NaN        NaN  20575701.0  39112.0         NaN
1983            NaN        NaN  21228288.0  40862.0         NaN
1984            NaN  2904429.0  21893857.0  42704.0         NaN
1985            NaN  2964762.0  22565908.0  44597.0   9745209.0
1986            NaN  3022635.0  23241276.0  46515.0  10023700.0
1987            NaN  3083605.0  23917889.0  48458.0  10285712.0
1988            NaN  3142336.0  24591493.0  50431.0  10544904.0
1989            NaN  3227943.0  25257671.0  52449.0  10820992.0
1990            NaN  3286542.0  25912364.0  54511.0  11127870.0
1991            NaN  3266790.0  26554277.0  56674.0  11472173.0
1992            NaN  3247039.0  27180921.0  58904.0  11848971.0
1993            NaN  3227287.0  27785977.0  61003.0  12246786.0
1994            NaN  3207536.0  28362015.0  62707.0  12648483.0
1995            NaN  3187784.0  28904300.0  63854.0  13042666.0
1996            NaN  3168033.0  29411839.0  64291.0  13424813.0
1997            NaN  3148281.0  29887717.0  64147.0  13801868.0
1998            NaN  3128530.0  30336880.0  63888.0  14187710.0
1999            NaN  3108778.0  30766551.0  64161.0  14601983.0
2000            NaN  3089027.0  31183658.0  65399.0  15058638.0
2001     20531160.0  3060173.0  31590320.0  67770.0  15562791.0
2002     21487079.0  3051010.0  31990387.0  71046.0  16109696.0
2003     22507368.0  3039616.0  32394886.0  74783.0  16691395.0
2004     23499850.0  3026939.0  32817225.0  78337.0  17295500.0
2005     24399948.0  3011487.0  33267887.0  81223.0  17912942.0
2006     25183615.0  2992547.0  33749328.0  83373.0  18541467.0
2007     25877544.0  2970017.0  34261971.0  84878.0  19183907.0
2008     26528741.0  2947314.0  34811059.0  85616.0  19842251.0
2009     27207291.0  2927519.0  35401790.0  85474.0  20520103.0
2010     27962207.0  2913021.0  36036159.0  84419.0  21219954.0
2011     28809167.0  2904780.0  36717132.0  82326.0  21942296.0
2012     29726803.0  2900247.0  37439427.0  79316.0  22685632.0
2013     30682500.0  2896652.0  38186135.0  75902.0  23448202.0
2014     31627506.0  2893654.0  38934334.0      NaN  24227524.0
2015     32526562.0  2889167.0  39666519.0      NaN  25021974.0

                                                                           \
country Antigua and Barbuda   Arab World   Argentina    Armenia     Aruba
year
1960                    NaN          NaN         NaN        NaN       NaN
1961                    NaN          NaN         NaN        NaN       NaN
1962                    NaN          NaN  21287682.0        NaN       NaN
1963                    NaN          NaN  21621845.0        NaN       NaN
1964                    NaN          NaN  21953926.0        NaN       NaN
1965                    NaN          NaN  22283389.0        NaN       NaN
1966                    NaN          NaN  22608747.0        NaN       NaN
1967                    NaN          NaN  22932201.0        NaN       NaN
1968                    NaN  115557094.0  23261273.0        NaN       NaN
1969                    NaN  118823872.0  23605992.0        NaN       NaN
1970                    NaN  122128175.0  23973062.0        NaN       NaN
1971                    NaN  125439089.0  24366442.0        NaN       NaN
1972                    NaN  128801209.0  24782950.0        NaN       NaN
1973                    NaN  132298955.0  25213388.0        NaN       NaN
1974                    NaN  136044481.0  25644505.0        NaN       NaN
1975                    NaN  140114424.0  26066975.0        NaN       NaN
1976                    NaN  144542039.0  26477153.0        NaN       NaN
1977                70223.0  149296257.0  26878567.0        NaN       NaN
1978                70508.0  154303887.0  27277742.0        NaN       NaN
1979                70553.0  159455867.0  27684530.0        NaN       NaN
1980                70301.0  164670713.0  28105889.0        NaN       NaN
1981                69750.0  169926632.0  28543366.0        NaN       NaN
1982                68950.0  175237742.0  28993989.0        NaN       NaN
1983                67958.0  180606318.0  29454739.0        NaN       NaN
1984                66863.0  186005735.0  29920907.0        NaN       NaN
1985                65744.0  191564251.0  30388781.0        NaN       NaN
1986                64605.0  197202142.0  30857242.0        NaN       NaN
1987                63484.0  202851923.0  31326473.0        NaN       NaN
1988                62538.0  208546282.0  31795515.0        NaN       NaN
1989                61967.0  214250542.0  32263559.0        NaN       NaN
1990                61906.0  222117305.0  32729740.0  3544695.0       NaN
1991                62412.0  228171034.0  33193920.0  3511912.0       NaN
1992                63434.0  232417246.0  33655149.0  3449497.0       NaN
1993                64868.0  238628852.0  34110912.0  3369673.0       NaN
1994                66550.0  244893420.0  34558114.0  3289943.0   76700.0
1995                68349.0  252591048.0  34994818.0  3223173.0   80326.0
1996                70245.0  258423164.0  35419683.0  3173425.0   83195.0
1997                72232.0  264153948.0  35833965.0  3137652.0   85447.0
1998                74206.0  269795252.0  36241578.0  3112958.0   87276.0
1999                76041.0  275503565.0  36648054.0  3093820.0   89004.0
2000                77648.0  281326250.0  37057453.0  3076098.0   90858.0
2001                78972.0  287291826.0  37471535.0  3060036.0   92894.0
2002                80030.0  293402563.0  37889443.0  3047249.0   94995.0
2003                80904.0  299731956.0  38309475.0  3036420.0   97015.0
2004                81718.0  306387415.0  38728778.0  3025982.0   98742.0
2005                82565.0  313430911.0  39145491.0  3014917.0  100031.0
2006                83467.0  320906736.0  39558750.0  3002161.0  100830.0
2007                84397.0  328766559.0  39969903.0  2988117.0  101218.0
2008                85350.0  336886468.0  40381860.0  2975029.0  101342.0
2009                86300.0  345054176.0  40798641.0  2966108.0  101416.0
2010                87233.0  353112237.0  41222875.0  2963496.0  101597.0
2011                88152.0  361031820.0  41655616.0  2967984.0  101936.0
2012                89069.0  368802611.0  42095224.0  2978339.0       NaN
2013                89985.0  376504253.0  42538304.0  2992192.0       NaN
2014                90900.0  384222592.0  42980026.0  3006154.0       NaN
2015                91818.0  392022276.0         NaN  3017712.0       NaN

         ...           GDP                                            \
country  ...    Uzbekistan       Vanuatu Venezuela, RB       Vietnam
year     ...
1960     ...           NaN           NaN  8.607600e+09           NaN
1961     ...           NaN           NaN  8.923367e+09           NaN
1962     ...           NaN           NaN  9.873398e+09           NaN
1963     ...           NaN           NaN  1.066338e+10           NaN
1964     ...           NaN           NaN  9.113581e+09           NaN
1965     ...           NaN           NaN  9.602945e+09           NaN
1966     ...           NaN           NaN  1.009657e+10           NaN
1967     ...           NaN           NaN  1.047278e+10           NaN
1968     ...           NaN           NaN  1.147091e+10           NaN
1969     ...           NaN           NaN  1.192757e+10           NaN
1970     ...           NaN           NaN  1.299312e+10           NaN
1971     ...           NaN           NaN  1.447156e+10           NaN
1972     ...           NaN           NaN  1.592287e+10           NaN
1973     ...           NaN           NaN  1.944593e+10           NaN
1974     ...           NaN           NaN  2.908710e+10           NaN
1975     ...           NaN           NaN  3.141316e+10           NaN
1976     ...           NaN           NaN  3.627232e+10           NaN
1977     ...           NaN           NaN  4.233706e+10           NaN
1978     ...           NaN           NaN  4.650764e+10           NaN
1979     ...           NaN  1.192588e+08  5.575055e+10           NaN
1980     ...           NaN  1.134232e+08  6.713512e+10           NaN
1981     ...           NaN  9.874641e+07  7.549883e+10           NaN
1982     ...           NaN  9.814464e+07  7.669365e+10           NaN
1983     ...           NaN  1.101238e+08  7.858650e+10           NaN
1984     ...           NaN  1.355538e+08  5.595234e+10           NaN
1985     ...           NaN  1.236985e+08  5.793574e+10  1.409469e+10
1986     ...           NaN  1.186914e+08  5.891511e+10  2.633662e+10
1987     ...           NaN  1.308341e+08  4.534379e+10  3.665811e+10
1988     ...           NaN  1.485454e+08  5.842840e+10  2.542381e+10
1989     ...           NaN  1.444822e+08  4.214230e+10  6.293305e+09
1990     ...  1.336061e+10  1.583974e+08  4.702751e+10  6.471740e+09
1991     ...  1.367762e+10  1.888700e+08  5.173436e+10  9.613370e+09
1992     ...  1.294130e+10  1.961426e+08  5.847036e+10  9.866990e+09
1993     ...  1.309901e+10  1.880804e+08  5.810756e+10  1.318095e+10
1994     ...  1.289916e+10  2.192603e+08  5.652990e+10  1.628643e+10
1995     ...  1.335047e+10  2.339021e+08  7.488874e+10  2.073616e+10
1996     ...  1.394889e+10  2.451776e+08  6.825859e+10  2.465747e+10
1997     ...  1.474460e+10  2.558902e+08  8.583739e+10  2.684370e+10
1998     ...  1.498897e+10  2.623013e+08  9.133854e+10  2.720960e+10
1999     ...  1.707847e+10  2.679992e+08  9.797414e+10  2.868366e+10
2000     ...  1.376037e+10  2.720147e+08  1.171476e+11  3.364009e+10
2001     ...  1.140135e+10  2.579269e+08  1.229097e+11  3.529135e+10
2002     ...  9.687951e+09  2.626038e+08  9.288959e+10  3.794790e+10
2003     ...  1.012811e+10  3.144631e+08  8.362219e+10  4.271707e+10
2004     ...  1.203002e+10  3.649969e+08  1.124514e+11  4.942411e+10
2005     ...  1.430751e+10  3.949626e+08  1.455135e+11  5.763326e+10
2006     ...  1.703090e+10  4.393768e+08  1.834775e+11  6.637166e+10
2007     ...  2.231139e+10  5.264283e+08  2.303642e+11  7.741443e+10
2008     ...  2.793403e+10  6.079586e+08  3.156002e+11  9.913030e+10
2009     ...  3.281683e+10  6.100666e+08  3.294190e+11  1.060146e+11
2010     ...  3.933277e+10  7.008043e+08  3.938015e+11  1.159317e+11
2011     ...  4.532432e+10  7.921497e+08  3.164822e+11  1.355395e+11
2012     ...  5.118344e+10  7.817029e+08  3.812862e+11  1.558200e+11
2013     ...  5.679566e+10  8.017876e+08  3.713366e+11  1.712220e+11
2014     ...  6.313285e+10  8.149546e+08           NaN  1.862047e+11
2015     ...  6.673280e+10           NaN           NaN  1.935994e+11

                                                                              \
country Virgin Islands (U.S.) West Bank and Gaza         World   Yemen, Rep.
year
1960             2.420000e+07                NaN  1.364643e+12           NaN
1961             2.570000e+07                NaN  1.420440e+12           NaN
1962             3.690000e+07                NaN  1.524573e+12           NaN
1963             4.140000e+07                NaN  1.638187e+12           NaN
1964             5.380000e+07                NaN  1.799675e+12           NaN
1965             6.650000e+07                NaN  1.959900e+12           NaN
1966             8.410000e+07                NaN  2.125397e+12           NaN
1967             1.154000e+08                NaN  2.262923e+12           NaN
1968             1.738000e+08                NaN  2.440549e+12           NaN
1969             2.113000e+08                NaN  2.686747e+12           NaN
1970             2.190000e+08                NaN  2.950656e+12           NaN
1971             2.570000e+08                NaN  3.259057e+12           NaN
1972             3.071000e+08                NaN  3.757853e+12           NaN
1973             3.516000e+08                NaN  4.578523e+12           NaN
1974             3.954000e+08                NaN  5.279355e+12           NaN
1975             3.998000e+08                NaN  5.880305e+12           NaN
1976             4.400000e+08                NaN  6.400883e+12           NaN
1977             4.618000e+08                NaN  7.237905e+12           NaN
1978             5.129000e+08                NaN  8.521725e+12           NaN
1979             6.067000e+08                NaN  9.903841e+12           NaN
1980             7.278000e+08                NaN  1.115409e+13           NaN
1981             8.218000e+08                NaN  1.144748e+13           NaN
1982             8.326000e+08                NaN  1.134460e+13           NaN
1983             9.169000e+08                NaN  1.160740e+13           NaN
1984             9.854000e+08                NaN  1.204953e+13           NaN
1985             9.904000e+08                NaN  1.267287e+13           NaN
1986             1.035600e+09                NaN  1.499712e+13           NaN
1987             1.147800e+09                NaN  1.706395e+13           NaN
1988             1.204600e+09                NaN  1.910918e+13           NaN
1989             1.343900e+09                NaN  2.006077e+13           NaN
1990             1.564700e+09                NaN  2.256312e+13  5.647252e+09
1991             1.671200e+09                NaN  2.389846e+13  5.930370e+09
1992             1.770900e+09                NaN  2.537482e+13  6.463650e+09
1993             1.996000e+09                NaN  2.580571e+13  5.368271e+09
1994                      NaN       2.843300e+09  2.770637e+13  4.167356e+09
1995                      NaN       3.282800e+09  3.065894e+13  4.258789e+09
1996                      NaN       3.409600e+09  3.132499e+13  5.785685e+09
1997                      NaN       3.759800e+09  3.124076e+13  6.839039e+09
1998                      NaN       4.067800e+09  3.112270e+13  6.325220e+09
1999                      NaN       4.271200e+09  3.228297e+13  7.641101e+09
2000                      NaN       4.313600e+09  3.332130e+13  9.636342e+09
2001                      NaN       4.003700e+09  3.313421e+13  9.854042e+09
2002                      NaN       3.555800e+09  3.441805e+13  1.069328e+10
2003                      NaN       3.968000e+09  3.865630e+13  1.177777e+10
2004                      NaN       4.329200e+09  4.355213e+13  1.387350e+10
2005                      NaN       4.831800e+09  4.714259e+13  1.675377e+10
2006                      NaN       4.910100e+09  5.107451e+13  1.908173e+10
2007                      NaN       5.505800e+09  5.758343e+13  2.563367e+10
2008                      NaN       6.673500e+09  6.312856e+13  3.039720e+10
2009                      NaN       7.268200e+09  5.983553e+13  2.845950e+10
2010                      NaN       8.913100e+09  6.564782e+13  3.090675e+10
2011                      NaN       1.045985e+10  7.284314e+13  3.107886e+10
2012                      NaN       1.127940e+10  7.442836e+13  3.207477e+10
2013                      NaN       1.247600e+10  7.643132e+13  3.595450e+10
2014                      NaN       1.271560e+10  7.810634e+13           NaN
2015                      NaN       1.267740e+10  7.343364e+13           NaN


country        Zambia      Zimbabwe
year
1960     6.987397e+08  1.052990e+09
1961     6.823597e+08  1.096647e+09
1962     6.792797e+08  1.117602e+09
1963     7.043397e+08  1.159512e+09
1964     8.226397e+08  1.217138e+09
1965     1.061200e+09  1.311436e+09
1966     1.239000e+09  1.281750e+09
1967     1.340639e+09  1.397002e+09
1968     1.573739e+09  1.479600e+09
1969     1.926399e+09  1.747999e+09
1970     1.788779e+09  1.884206e+09
1971     1.653259e+09  2.178716e+09
1972     1.872417e+09  2.677729e+09
1973     2.434255e+09  3.309354e+09
1974     2.910981e+09  3.982161e+09
1975     2.442672e+09  4.371301e+09
1976     2.742859e+09  4.318372e+09
1977     2.515297e+09  4.364382e+09
1978     2.811032e+09  4.351600e+09
1979     3.353445e+09  5.177459e+09
1980     3.884531e+09  6.678868e+09
1981     4.008126e+09  8.011374e+09
1982     3.871117e+09  8.539701e+09
1983     3.321048e+09  7.764067e+09
1984     2.719519e+09  6.352126e+09
1985     2.252455e+09  5.637259e+09
1986     1.664414e+09  6.217524e+09
1987     2.265251e+09  6.741215e+09
1988     3.728878e+09  7.814784e+09
1989     3.994673e+09  8.286323e+09
1990     3.288382e+09  8.783817e+09
1991     3.378882e+09  8.641482e+09
1992     3.181922e+09  6.751472e+09
1993     3.273238e+09  6.563813e+09
1994     3.656648e+09  6.890675e+09
1995     3.807067e+09  7.111271e+09
1996     3.597221e+09  8.553147e+09
1997     4.303282e+09  8.529572e+09
1998     3.537683e+09  6.401968e+09
1999     3.404312e+09  6.858013e+09
2000     3.600683e+09  6.689958e+09
2001     4.094481e+09  6.777385e+09
2002     4.193846e+09  6.342116e+09
2003     4.901840e+09  5.727592e+09
2004     6.221078e+09  5.805598e+09
2005     8.331870e+09  5.755215e+09
2006     1.275686e+10  5.443896e+09
2007     1.405696e+10  5.291950e+09
2008     1.791086e+10  4.415703e+09
2009     1.532834e+10  8.157077e+09
2010     2.026555e+10  9.422161e+09
2011     2.345952e+10  1.095623e+10
2012     2.550306e+10  1.239272e+10
2013     2.804552e+10  1.349023e+10
2014     2.713464e+10  1.419691e+10
2015     2.120156e+10  1.389294e+10

[56 rows x 504 columns]

In [45]:
len(s.pivot(index='year',columns='country',values=['Population','GDP']))

56

In [ ]:
len()