# The .unstack() Method, Part 3

In [24]:
import pandas as pd

In [25]:
%%html
<style>
    table.dataframe th,table.dataframe td{
        border:1px solid black;
        background-color:white;
    }
</style>

In [26]:
world = pd.read_csv('../worldstats.csv',index_col=['country','year'])
s = world.stack()
s.head().to_frame()

                                       0
country    year
Arab World 2015 Population  3.920223e+08
                GDP         2.530102e+12
           2014 Population  3.842226e+08
                GDP         2.873600e+12
           2013 Population  3.765043e+08

In [27]:
s.unstack(level=[2,1])
s.unstack(level=['year','country'])

year,2015,2014,2013,2012,2011,2010,2009,2008,2007,2006,...,1969,1968,1967,1966,1965,1964,1963,1962,1961,1960
country,Arab World,Arab World,Arab World,Arab World,Arab World,Arab World,Arab World,Arab World,Arab World,Arab World,...,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe,Zimbabwe
Population,3.920223e+08,3.842226e+08,3.765043e+08,3.688026e+08,3.610318e+08,3.531122e+08,3.450542e+08,3.368865e+08,3.287666e+08,3.209067e+08,...,5.036321e+06,4.874113e+06,4.718612e+06,4.568320e+06,4.422132e+06,4.279561e+06,4.140804e+06,4.006262e+06,3.876638e+06,3.752390e+06
GDP,2.530102e+12,2.873600e+12,2.846994e+12,2.773270e+12,2.497945e+12,2.103825e+12,1.798878e+12,2.081343e+12,1.641666e+12,1.404190e+12,...,1.747999e+09,1.479600e+09,1.397002e+09,1.281750e+09,1.311436e+09,1.217138e+09,1.159512e+09,1.117602e+09,1.096647e+09,1.052990e+09

In [29]:
s.unstack('year',fill_value=0)

year                            1960          1961          1962  \
country
Afghanistan Population  8.994793e+06  9.164945e+06  9.343772e+06
            GDP         5.377778e+08  5.488889e+08  5.466667e+08
Albania     Population  0.000000e+00  0.000000e+00  0.000000e+00
            GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria     Population  1.112489e+07  1.140486e+07  1.169015e+07
...                              ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia      Population  3.049586e+06  3.142848e+06  3.240664e+06
            GDP         6.987397e+08  6.823597e+08  6.792797e+08
Zimbabwe    Population  3.752390e+06  3.876638e+06  4.006262e+06
            GDP         1.052990e+09  1.096647e+09  1.117602e+09

year                            1963          1964          1965  \
country
Afghanistan Population  9.531555e+06  9.728645e+06  9.935358e+06
            GDP         7.511112e+08  8.000000e+08  1.006667e+09
Albania     Population  0.000000e+00  0.000000e+00  0.000000e+00
            GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria     Population  1.198513e+07  1.229597e+07  1.262695e+07
...                              ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia      Population  3.342894e+06  3.449266e+06  3.559687e+06
            GDP         7.043397e+08  8.226397e+08  1.061200e+09
Zimbabwe    Population  4.140804e+06  4.279561e+06  4.422132e+06
            GDP         1.159512e+09  1.217138e+09  1.311436e+09

year                            1966          1967          1968  \
country
Afghanistan Population  1.014884e+07  1.036860e+07  1.059979e+07
            GDP         1.400000e+09  1.673333e+09  1.373333e+09
Albania     Population  0.000000e+00  0.000000e+00  0.000000e+00
            GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria     Population  1.298027e+07  1.335420e+07  1.374438e+07
...                              ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia      Population  3.674088e+06  3.792864e+06  3.916928e+06
            GDP         1.239000e+09  1.340639e+09  1.573739e+09
Zimbabwe    Population  4.568320e+06  4.718612e+06  4.874113e+06
            GDP         1.281750e+09  1.397002e+09  1.479600e+09

year                            1969  ...          2006          2007  \
country                               ...
Afghanistan Population  1.084951e+07  ...  2.518362e+07  2.587754e+07
            GDP         1.408889e+09  ...  7.057598e+09  9.843842e+09
Albania     Population  0.000000e+00  ...  2.992547e+06  2.970017e+06
            GDP         0.000000e+00  ...  8.992642e+09  1.070101e+10
Algeria     Population  1.414444e+07  ...  3.374933e+07  3.426197e+07
...                              ...  ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  ...  1.908173e+10  2.563367e+10
Zambia      Population  4.047479e+06  ...  1.238151e+07  1.273868e+07
            GDP         1.926399e+09  ...  1.275686e+10  1.405696e+10
Zimbabwe    Population  5.036321e+06  ...  1.312794e+07  1.329780e+07
            GDP         1.747999e+09  ...  5.443896e+09  5.291950e+09

year                            2008          2009          2010  \
country
Afghanistan Population  2.652874e+07  2.720729e+07  2.796221e+07
            GDP         1.019053e+10  1.248694e+10  1.593680e+10
Albania     Population  2.947314e+06  2.927519e+06  2.913021e+06
            GDP         1.288135e+10  1.204421e+10  1.192695e+10
Algeria     Population  3.481106e+07  3.540179e+07  3.603616e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.039720e+10  2.845950e+10  3.090675e+10
Zambia      Population  1.311458e+07  1.350785e+07  1.391744e+07
            GDP         1.791086e+10  1.532834e+10  2.026555e+10
Zimbabwe    Population  1.349546e+07  1.372100e+07  1.397390e+07
            GDP         4.415703e+09  8.157077e+09  9.422161e+09

year                            2011          2012          2013  \
country
Afghanistan Population  2.880917e+07  2.972680e+07  3.068250e+07
            GDP         1.793024e+10  2.053654e+10  2.004633e+10
Albania     Population  2.904780e+06  2.900247e+06  2.896652e+06
            GDP         1.289087e+10  1.231978e+10  1.278103e+10
Algeria     Population  3.671713e+07  3.743943e+07  3.818614e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.107886e+10  3.207477e+10  3.595450e+10
Zambia      Population  1.434353e+07  1.478658e+07  1.524609e+07
            GDP         2.345952e+10  2.550306e+10  2.804552e+10
Zimbabwe    Population  1.425559e+07  1.456548e+07  1.489809e+07
            GDP         1.095623e+10  1.239272e+10  1.349023e+10

year                            2014          2015
country
Afghanistan Population  3.162751e+07  3.252656e+07
            GDP         2.005019e+10  1.919944e+10
Albania     Population  2.893654e+06  2.889167e+06
            GDP         1.327796e+10  1.145560e+10
Algeria     Population  3.893433e+07  3.966652e+07
...                              ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00
Zambia      Population  1.572134e+07  1.621177e+07
            GDP         2.713464e+10  2.120156e+10
Zimbabwe    Population  1.524586e+07  1.560275e+07
            GDP         1.419691e+10  1.389294e+10

[504 rows x 56 columns]

In [30]:
s = s.unstack('year',fill_value=0)

In [31]:
s

year                            1960          1961          1962  \
country
Afghanistan Population  8.994793e+06  9.164945e+06  9.343772e+06
            GDP         5.377778e+08  5.488889e+08  5.466667e+08
Albania     Population  0.000000e+00  0.000000e+00  0.000000e+00
            GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria     Population  1.112489e+07  1.140486e+07  1.169015e+07
...                              ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia      Population  3.049586e+06  3.142848e+06  3.240664e+06
            GDP         6.987397e+08  6.823597e+08  6.792797e+08
Zimbabwe    Population  3.752390e+06  3.876638e+06  4.006262e+06
            GDP         1.052990e+09  1.096647e+09  1.117602e+09

year                            1963          1964          1965  \
country
Afghanistan Population  9.531555e+06  9.728645e+06  9.935358e+06
            GDP         7.511112e+08  8.000000e+08  1.006667e+09
Albania     Population  0.000000e+00  0.000000e+00  0.000000e+00
            GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria     Population  1.198513e+07  1.229597e+07  1.262695e+07
...                              ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia      Population  3.342894e+06  3.449266e+06  3.559687e+06
            GDP         7.043397e+08  8.226397e+08  1.061200e+09
Zimbabwe    Population  4.140804e+06  4.279561e+06  4.422132e+06
            GDP         1.159512e+09  1.217138e+09  1.311436e+09

year                            1966          1967          1968  \
country
Afghanistan Population  1.014884e+07  1.036860e+07  1.059979e+07
            GDP         1.400000e+09  1.673333e+09  1.373333e+09
Albania     Population  0.000000e+00  0.000000e+00  0.000000e+00
            GDP         0.000000e+00  0.000000e+00  0.000000e+00
Algeria     Population  1.298027e+07  1.335420e+07  1.374438e+07
...                              ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00  0.000000e+00
Zambia      Population  3.674088e+06  3.792864e+06  3.916928e+06
            GDP         1.239000e+09  1.340639e+09  1.573739e+09
Zimbabwe    Population  4.568320e+06  4.718612e+06  4.874113e+06
            GDP         1.281750e+09  1.397002e+09  1.479600e+09

year                            1969  ...          2006          2007  \
country                               ...
Afghanistan Population  1.084951e+07  ...  2.518362e+07  2.587754e+07
            GDP         1.408889e+09  ...  7.057598e+09  9.843842e+09
Albania     Population  0.000000e+00  ...  2.992547e+06  2.970017e+06
            GDP         0.000000e+00  ...  8.992642e+09  1.070101e+10
Algeria     Population  1.414444e+07  ...  3.374933e+07  3.426197e+07
...                              ...  ...           ...           ...
Yemen, Rep. GDP         0.000000e+00  ...  1.908173e+10  2.563367e+10
Zambia      Population  4.047479e+06  ...  1.238151e+07  1.273868e+07
            GDP         1.926399e+09  ...  1.275686e+10  1.405696e+10
Zimbabwe    Population  5.036321e+06  ...  1.312794e+07  1.329780e+07
            GDP         1.747999e+09  ...  5.443896e+09  5.291950e+09

year                            2008          2009          2010  \
country
Afghanistan Population  2.652874e+07  2.720729e+07  2.796221e+07
            GDP         1.019053e+10  1.248694e+10  1.593680e+10
Albania     Population  2.947314e+06  2.927519e+06  2.913021e+06
            GDP         1.288135e+10  1.204421e+10  1.192695e+10
Algeria     Population  3.481106e+07  3.540179e+07  3.603616e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.039720e+10  2.845950e+10  3.090675e+10
Zambia      Population  1.311458e+07  1.350785e+07  1.391744e+07
            GDP         1.791086e+10  1.532834e+10  2.026555e+10
Zimbabwe    Population  1.349546e+07  1.372100e+07  1.397390e+07
            GDP         4.415703e+09  8.157077e+09  9.422161e+09

year                            2011          2012          2013  \
country
Afghanistan Population  2.880917e+07  2.972680e+07  3.068250e+07
            GDP         1.793024e+10  2.053654e+10  2.004633e+10
Albania     Population  2.904780e+06  2.900247e+06  2.896652e+06
            GDP         1.289087e+10  1.231978e+10  1.278103e+10
Algeria     Population  3.671713e+07  3.743943e+07  3.818614e+07
...                              ...           ...           ...
Yemen, Rep. GDP         3.107886e+10  3.207477e+10  3.595450e+10
Zambia      Population  1.434353e+07  1.478658e+07  1.524609e+07
            GDP         2.345952e+10  2.550306e+10  2.804552e+10
Zimbabwe    Population  1.425559e+07  1.456548e+07  1.489809e+07
            GDP         1.095623e+10  1.239272e+10  1.349023e+10

year                            2014          2015
country
Afghanistan Population  3.162751e+07  3.252656e+07
            GDP         2.005019e+10  1.919944e+10
Albania     Population  2.893654e+06  2.889167e+06
            GDP         1.327796e+10  1.145560e+10
Algeria     Population  3.893433e+07  3.966652e+07
...                              ...           ...
Yemen, Rep. GDP         0.000000e+00  0.000000e+00
Zambia      Population  1.572134e+07  1.621177e+07
            GDP         2.713464e+10  2.120156e+10
Zimbabwe    Population  1.524586e+07  1.560275e+07
            GDP         1.419691e+10  1.389294e+10

[504 rows x 56 columns]