# Filter with More than One Condition (OR)

In [2]:
import pandas as pd

In [3]:
%%HTML
<style>
table.dataframe th,table.dataframe td{
    border:1px solid black;
    background-color:white;
}
</style>

In [4]:
pd.set_option('display.max_row',None)
df = pd.read_csv('../employees.csv')
df.head(4)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance

In [5]:
df['Gender'] = df['Gender'].astype('category')
df['Start Date'] = pd.to_datetime(df['Start Date'])
df['Team'] = df['Team'].astype('category')
df['Senior Management'] = df['Senior Management'].astype('bool')
df['Last Login Time'] = pd.to_datetime(df['Last Login Time'])

In [8]:
manager = df['Senior Management']
dob = df['Start Date']<'1/2/1999'
df[manager | dob]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2020-11-26 12:42:00,97308,6.945,True,Marketing
1,Thomas,Male,1996-03-31,2020-11-26 06:53:00,61933,4.170,True,NaN
2,Maria,Female,1993-04-23,2020-11-26 11:17:00,130590,11.858,False,Finance
3,Jerry,Male,2005-03-04,2020-11-26 13:00:00,138705,9.340,True,Finance
4,Larry,Male,1998-01-24,2020-11-26 16:47:00,101004,1.389,True,Client Services
5,Dennis,Male,1987-04-18,2020-11-26 01:35:00,115163,10.125,False,Legal
6,Ruby,Female,1987-08-17,2020-11-26 16:20:00,65476,10.012,True,Product
7,NaN,Female,2015-07-20,2020-11-26 10:43:00,45906,11.598,True,Finance
8,Angela,Female,2005-11-22,2020-11-26 06:29:00,95570,18.523,True,Engineering
9,Frances,Female,2002-08-08,2020-11-26 06:51:00,139852,7.524,True,Business Development
10,Louise,Female,1980-08-12,2020-11-26 09:01:00,63241,15.132,True,NaN
11,Julie,Female,1997-10-26,2020-11-26 15:19:00,102508,12.637,True,Legal
12,Brandon,Male,1980-12-01,2020-11-26 01:08:00,112807,17.492,True,Human Resources
14,Kimberly,Female,1999-01-14,2020-11-26 07:13:00,41426,14.543,True,Finance
17,Shawn,Male,1986-12-07,2020-11-26 19:45:00,111737,6.414,False,Product
18,Diana,Female,1981-10-23,2020-11-26 10:27:00,132940,19.082,False,Client Services
20,Lois,NaN,1995-04-22,2020-11-26 19:18:00,64714,4.934,True,Legal
21,Matthew,Male,1995-09-05,2020-11-26 02:12:00,100612,13.645,False,Marketing
22,Joshua,NaN,2012-03-08,2020-11-26 01:58:00,90816,18.816,True,Client Services
23,NaN,Male,2012-06-14,2020-11-26 16:19:00,125792,5.042,True,NaN
24,John,Male,1992-07-01,2020-11-26 22:08:00,97950,13.873,False,Client Services
25,NaN,Male,2012-10-08,2020-11-26 01:12:00,37076,18.576,True,Client Services
26,Craig,Male,2000-02-27,2020-11-26 07:45:00,37598,7.757,True,Marketing
27,Scott,NaN,1991-07-11,2020-11-26 18:58:00,122367,5.218,False,Legal
28,Terry,Male,1981-11-27,2020-11-26 18:30:00,124008,13.464,True,Client Services
29,Benjamin,Male,2005-01-26,2020-11-26 22:06:00,79529,7.008,True,Legal
30,Christina,Female,2002-08-06,2020-11-26 13:19:00,118780,9.096,True,Engineering
32,NaN,Male,1998-08-21,2020-11-26 14:27:00,122340,6.417,True,NaN
33,Jean,Female,1993-12-18,2020-11-26 09:07:00,119082,16.180,False,Business Development
37,Linda,Female,1981-10-19,2020-11-26 20:49:00,57427,9.557,True,Client Services
38,Stephanie,Female,1986-09-13,2020-11-26 01:52:00,36844,5.574,True,Business Development
39,NaN,Male,2016-01-29,2020-11-26 02:33:00,122173,7.797,True,Client Services
40,Michael,Male,2008-10-10,2020-11-26 11:25:00,99283,2.665,True,Distribution
41,Christine,NaN,2015-06-28,2020-11-26 01:08:00,66582,11.308,True,Business Development
42,Beverly,Female,1998-09-09,2020-11-26 20:26:00,121918,15.835,False,Legal
43,Marilyn,Female,1980-12-07,2020-11-26 03:16:00,73524,5.207,True,Marketing
44,Cynthia,Female,1988-11-16,2020-11-26 18:54:00,145146,7.482,True,Product
45,Roger,Male,1980-04-17,2020-11-26 11:32:00,88010,13.886,True,Sales
47,Kathy,Female,2005-06-22,2020-11-26 04:51:00,66820,9.000,True,Client Services
48,Clarence,Male,1996-03-26,2020-11-26 05:57:00,93581,6.083,True,Business Development
49,Chris,NaN,1980-01-24,2020-11-26 12:13:00,113590,3.055,False,Sales
50,Nancy,Female,2000-09-23,2020-11-26 08:05:00,94976,13.830,True,Engineering
51,NaN,NaN,2011-12-17,2020-11-26 08:29:00,41126,14.009,True,Sales
52,Todd,Male,1990-02-18,2020-11-26 02:41:00,49339,1.695,True,Human Resources
53,Alan,NaN,2014-03-03,2020-11-26 13:28:00,40341,17.578,True,Finance
55,Karen,Female,1999-11-30,2020-11-26 07:46:00,102488,17.653,True,Product
56,Carl,Male,2006-05-03,2020-11-26 17:55:00,130276,16.084,True,Finance
57,Henry,Male,1996-06-26,2020-11-26 01:44:00,64715,15.107,True,Human Resources
58,Theresa,Female,2010-04-11,2020-11-26 07:18:00,72670,1.481,True,Engineering
59,Irene,Female,1997-05-07,2020-11-26 09:32:00,66851,11.279,False,Engineering
62,NaN,Female,2007-06-12,2020-11-26 17:25:00,58112,19.414,True,Marketing
64,Kathleen,NaN,1990-04-11,2020-11-26 18:46:00,77834,18.771,False,Business Development
65,Steve,Male,2009-11-11,2020-11-26 23:44:00,61310,12.428,True,Distribution
66,Nancy,Female,2012-12-15,2020-11-26 23:57:00,125250,2.672,True,Business Development
67,Rachel,Female,1999-08-16,2020-11-26 06:53:00,51178,9.735,True,Finance
68,Jose,Male,2004-10-30,2020-11-26 13:39:00,84834,14.330,True,Finance
69,Irene,NaN,2015-07-14,2020-11-26 16:31:00,100863,4.382,True,Finance
71,Johnny,Male,2009-11-06,2020-11-26 16:23:00,118172,16.194,True,Sales
73,Frances,Female,1999-04-04,2020-11-26 16:19:00,90582,4.709,True,Sales
74,Thomas,Male,1995-06-04,2020-11-26 14:24:00,62096,17.029,False,Marketing
75,Bonnie,Female,1991-07-02,2020-11-26 01:27:00,104897,5.118,True,Human Resources
76,Margaret,Female,1988-09-10,2020-11-26 12:42:00,131604,7.353,True,Distribution
77,Charles,Male,2004-09-14,2020-11-26 20:13:00,107391,1.260,True,Marketing
78,Robin,Female,1983-06-04,2020-11-26 15:15:00,114797,5.965,True,Sales
79,Bonnie,Female,1988-11-13,2020-11-26 15:30:00,115814,4.990,False,Product
80,Gerald,NaN,1995-03-17,2020-11-26 00:50:00,137126,15.602,True,Sales
82,Steven,Male,1980-03-30,2020-11-26 21:20:00,35095,8.379,True,Client Services
83,Shawn,Male,2005-09-23,2020-11-26 02:55:00,148115,6.539,True,Finance
85,Jeremy,Male,2008-02-01,2020-11-26 08:50:00,100238,3.887,True,Client Services
86,Annie,NaN,2007-09-29,2020-11-26 00:11:00,103495,17.290,True,Business Development
87,Annie,Female,1993-01-30,2020-11-26 02:05:00,144887,8.276,True,Sales
88,Donna,Female,1991-11-27,2020-11-26 13:59:00,64088,6.155,True,Legal
90,Janice,NaN,1997-08-21,2020-11-26 05:12:00,91719,11.583,True,Legal
92,Linda,Female,2000-05-25,2020-11-26 17:45:00,119009,12.506,True,Business Development
93,Virginia,NaN,1994-05-07,2020-11-26 17:58:00,111858,1.601,True,Legal
94,Harry,Male,1981-08-26,2020-11-26 15:16:00,130620,7.030,False,Legal
95,Heather,Female,1998-07-11,2020-11-26 14:17:00,43026,14.166,False,Client Services
96,Cynthia,Female,1994-03-21,2020-11-26 08:34:00,142321,1.737,False,Finance
97,Laura,NaN,2014-07-19,2020-11-26 21:23:00,140371,10.620,True,Marketing
98,Tina,Female,2016-06-16,2020-11-26 19:47:00,100705,16.961,True,Marketing
99,Harold,Male,1985-01-02,2020-11-26 21:40:00,77544,12.447,False,Business Development
101,Aaron,Male,2012-02-17,2020-11-26 10:20:00,61602,11.849,True,Marketing
102,Jack,Male,1997-01-12,2020-11-26 05:51:00,103902,12.159,False,Client Services
103,Phyllis,Female,1996-10-11,2020-11-26 21:30:00,136984,8.932,True,Finance
104,John,Male,1989-12-23,2020-11-26 07:01:00,80740,19.305,False,Marketing
105,Kathy,Female,1996-03-09,2020-11-26 04:33:00,91712,8.567,False,Finance
106,Paul,Male,1993-08-04,2020-11-26 19:25:00,42146,3.046,False,Legal
108,Russell,NaN,1988-05-05,2020-11-26 07:57:00,133980,12.396,True,Legal
111,Bonnie,Female,1999-12-17,2020-11-26 15:12:00,42153,8.454,True,Business Development
113,Tina,Female,2009-06-12,2020-11-26 07:16:00,114767,3.711,True,Engineering
114,Ashley,Female,2002-08-04,2020-11-26 11:00:00,58698,6.811,True,Business Development
115,Pamela,Female,1982-07-01,2020-11-26 06:51:00,54585,4.166,False,Product
116,NaN,Male,1991-06-22,2020-11-26 20:58:00,76189,18.988,True,Legal
117,Steven,Male,1995-03-01,2020-11-26 15:03:00,109095,9.494,False,Finance
120,Peter,Male,1994-11-17,2020-11-26 18:15:00,84885,15.402,False,Business Development
122,Christina,Female,2012-04-13,2020-11-26 14:04:00,110169,13.892,True,Engineering
123,Helen,Female,2001-11-29,2020-11-26 02:30:00,73789,14.841,True,Product
124,Marilyn,Female,1983-11-16,2020-11-26 08:29:00,76078,2.401,True,Product
126,Michelle,Female,1984-03-30,2020-11-26 18:43:00,57325,17.179,True,Human Resources
128,Kenneth,Male,1987-08-25,2020-11-26 21:16:00,127654,16.439,True,Client Services
129,Antonio,Male,1988-10-25,2020-11-26 13:50:00,60866,13.101,True,Business Development
130,Shirley,Female,1984-05-01,2020-11-26 13:15:00,41334,6.219,True,Human Resources
131,Rebecca,Female,1992-07-10,2020-11-26 00:23:00,94231,17.517,False,Product
132,Carlos,Male,1995-01-04,2020-11-26 07:02:00,146670,10.763,False,Human Resources
133,Lois,Female,1987-12-25,2020-11-26 16:16:00,106317,2.235,True,Client Services
134,Carolyn,Female,2011-04-09,2020-11-26 05:38:00,109260,2.650,True,Business Development
135,Gloria,Female,2007-06-29,2020-11-26 05:34:00,134148,8.833,True,Legal
136,Henry,Male,1995-04-24,2020-11-26 04:18:00,43542,19.687,False,Legal
138,Ashley,Female,2006-05-25,2020-11-26 11:30:00,112238,6.030,True,Engineering
139,NaN,Female,1990-10-03,2020-11-26 01:08:00,132373,10.527,True,NaN
140,Shirley,Female,1981-02-28,2020-11-26 13:23:00,113850,1.854,False,Marketing
141,Adam,Male,1990-12-24,2020-11-26 20:57:00,110194,14.727,True,Product
143,Teresa,NaN,2016-01-28,2020-11-26 10:55:00,140013,8.689,True,Engineering
144,Nicole,NaN,1982-03-05,2020-11-26 14:28:00,122717,12.452,False,Sales
145,Jennifer,Female,2009-04-04,2020-11-26 22:47:00,71715,13.079,True,Client Services
146,Patricia,Female,1992-11-25,2020-11-26 02:24:00,95322,4.150,False,Product
148,Patrick,NaN,1991-07-14,2020-11-26 02:24:00,124488,14.837,True,Sales
149,NaN,Female,2014-08-17,2020-11-26 14:00:00,86230,8.578,True,Distribution
150,Sean,Male,1996-05-04,2020-11-26 20:59:00,135490,19.934,False,Marketing
151,Brandon,NaN,1997-11-03,2020-11-26 20:17:00,121333,15.295,False,Business Development
152,Ruth,Female,1999-08-19,2020-11-26 04:03:00,129297,8.067,True,Client Services
153,Victor,NaN,2011-03-10,2020-11-26 20:40:00,84546,10.489,True,Finance
154,Rebecca,Female,1980-11-15,2020-11-26 04:13:00,85730,5.359,True,Product
155,Marie,Female,2003-03-16,2020-11-26 00:12:00,104058,17.695,True,Business Development
156,Howard,Male,1992-04-27,2020-11-26 01:10:00,105062,1.563,False,Human Resources
157,NaN,Female,2005-07-27,2020-11-26 08:32:00,79536,14.443,True,Product
158,Norma,Female,1999-02-28,2020-11-26 20:45:00,114412,8.756,True,Marketing
159,James,NaN,1983-11-22,2020-11-26 22:52:00,68501,14.316,False,Marketing
160,Kathy,Female,2000-03-18,2020-11-26 19:26:00,149563,16.991,True,Finance
162,Arthur,Male,1998-04-13,2020-11-26 11:28:00,89786,14.422,True,Legal
163,Terry,Male,1990-09-03,2020-11-26 21:15:00,52226,19.135,False,Client Services
165,NaN,Female,2014-03-23,2020-11-26 13:28:00,59148,9.061,True,Legal
166,NaN,Female,1991-07-09,2020-11-26 18:52:00,42341,7.014,True,Sales
167,Christopher,Male,2011-12-24,2020-11-26 12:22:00,142178,17.984,True,Sales
168,Peter,NaN,1987-09-03,2020-11-26 17:59:00,38989,7.017,True,Marketing
169,Michelle,Female,1996-11-04,2020-11-26 21:34:00,53754,5.455,True,Product
170,Irene,Female,1992-01-29,2020-11-26 11:36:00,133772,19.020,True,Sales
171,Patrick,Male,2007-08-17,2020-11-26 03:16:00,143499,17.495,True,Engineering
172,Sara,Female,1991-09-23,2020-11-26 18:17:00,97058,9.402,False,Finance
173,Lillian,Female,2008-12-21,2020-11-26 18:51:00,85446,3.959,True,Engineering
174,NaN,NaN,2007-09-18,2020-11-26 18:59:00,40297,6.185,True,Client Services
175,Willie,Male,1998-02-17,2020-11-26 20:20:00,146651,1.451,True,Engineering
177,Wayne,Male,2012-04-07,2020-11-26 08:00:00,102652,14.085,True,Distribution
178,Jane,Female,1997-09-03,2020-11-26 02:01:00,144474,17.648,False,Product
179,Jessica,Female,1995-10-23,2020-11-26 05:53:00,68759,19.343,True,Finance
180,Mark,Male,2008-04-12,2020-11-26 17:40:00,57286,5.025,True,Business Development
181,Randy,Male,1999-11-14,2020-11-26 12:12:00,58129,1.952,True,Distribution
182,Lillian,Female,1999-06-19,2020-11-26 16:44:00,123940,12.184,True,Business Development
183,Ruth,NaN,1999-05-18,2020-11-26 05:56:00,98233,2.518,True,Distribution
184,Jerry,Male,2003-12-18,2020-11-26 06:46:00,140810,9.177,True,Client Services
185,Sandra,Female,1983-01-19,2020-11-26 07:25:00,42090,8.842,True,Legal
186,NaN,Female,2005-02-23,2020-11-26 21:50:00,149654,1.825,True,Sales
189,Clarence,Male,1998-05-02,2020-11-26 03:16:00,85700,1.215,False,Sales
190,Carol,Female,1996-03-19,2020-11-26 03:39:00,57783,9.129,False,Finance
192,Barbara,NaN,2003-05-03,2020-11-26 19:32:00,99326,16.475,True,Legal
193,Rebecca,Female,1995-02-18,2020-11-26 06:50:00,109259,4.443,True,Legal
195,Ronald,Male,2014-04-30,2020-11-26 14:19:00,121068,12.757,True,Product
196,Steven,Male,1985-11-10,2020-11-26 10:53:00,62719,19.127,False,Client Services
198,Maria,Female,1990-12-27,2020-11-26 21:57:00,36067,9.640,True,Product
199,Jonathan,Male,2009-07-17,2020-11-26 08:15:00,130581,16.736,True,NaN
200,Gary,Male,1987-08-12,2020-11-26 00:04:00,89661,8.525,False,Finance
201,Kimberly,Female,1997-07-15,2020-11-26 05:57:00,36643,7.953,False,Marketing
202,Roger,Male,1982-11-08,2020-11-26 02:32:00,140558,5.084,True,Sales
203,Diana,Female,2013-01-04,2020-11-26 07:53:00,103521,2.784,True,Business Development
204,Willie,Male,2006-06-06,2020-11-26 09:45:00,55281,4.935,True,Marketing
205,Brandon,Male,2006-03-27,2020-11-26 17:54:00,115711,8.012,True,Finance
206,Patricia,Female,2012-12-06,2020-11-26 04:01:00,114079,8.399,True,Client Services
208,Jonathan,Male,1987-10-12,2020-11-26 02:59:00,141069,4.903,False,Human Resources
210,Ruth,Female,1986-08-12,2020-11-26 19:29:00,44639,9.148,True,Legal
211,Linda,Female,2006-06-24,2020-11-26 12:04:00,110967,19.612,True,Human Resources
213,Evelyn,Female,1980-05-24,2020-11-26 23:10:00,81673,15.364,True,Engineering
214,Julie,Female,1989-07-23,2020-11-26 13:52:00,109588,3.550,False,Engineering
217,Douglas,Male,1999-09-03,2020-11-26 16:00:00,83341,1.015,True,Client Services
218,Gregory,NaN,1992-06-15,2020-11-26 05:08:00,98865,10.628,True,Finance
219,Billy,Male,1995-03-13,2020-11-26 12:05:00,120444,7.768,True,Finance
220,NaN,Female,1991-06-17,2020-11-26 12:49:00,71945,5.560,True,Marketing
223,Daniel,Male,2010-04-30,2020-11-26 03:48:00,106947,15.866,True,Legal
224,Sarah,Female,1995-09-14,2020-11-26 07:50:00,87298,2.311,False,Distribution
225,Harry,Male,2015-10-01,2020-11-26 19:47:00,64579,15.266,True,Sales
226,Kathy,Female,1995-04-19,2020-11-26 00:46:00,50905,9.404,True,Finance
227,Todd,Male,1999-04-13,2020-11-26 10:31:00,59728,11.226,True,Client Services
228,Bobby,Male,1994-09-23,2020-11-26 01:29:00,51685,17.445,True,Engineering
229,Jeremy,Male,2000-06-08,2020-11-26 00:15:00,49542,1.679,True,Distribution
230,George,NaN,1988-02-24,2020-11-26 11:29:00,38375,8.999,False,Legal
231,Diane,Female,1993-04-18,2020-11-26 03:22:00,64084,17.018,False,Product
232,Marilyn,Female,1997-04-04,2020-11-26 21:28:00,147663,10.263,False,Human Resources
234,Irene,Female,1982-02-04,2020-11-26 17:26:00,40837,12.182,True,Client Services
235,Norma,Female,2015-02-11,2020-11-26 23:44:00,94393,3.643,True,Engineering
238,Kevin,Male,1982-03-25,2020-11-26 07:31:00,35061,5.128,False,Legal
240,Phyllis,NaN,1984-04-21,2020-11-26 19:05:00,94088,19.107,False,Distribution
241,Walter,Male,1983-07-06,2020-11-26 23:54:00,127813,5.961,False,Finance
242,Robert,Male,1990-10-27,2020-11-26 19:15:00,38041,18.428,True,Engineering
243,Jimmy,Male,1986-10-07,2020-11-26 17:53:00,126310,5.413,True,Product
244,Clarence,Male,1996-10-08,2020-11-26 12:53:00,142561,8.866,False,Client Services
245,Victor,Male,1991-04-11,2020-11-26 07:44:00,70817,17.138,False,Engineering
246,Fred,NaN,1984-12-02,2020-11-26 14:03:00,59937,12.045,True,Human Resources
247,Brenda,NaN,2010-07-27,2020-11-26 23:07:00,106115,3.742,True,Product
248,Justin,Male,1992-12-06,2020-11-26 17:58:00,82782,4.366,True,Distribution
249,Betty,Female,2002-06-12,2020-11-26 03:59:00,104896,19.550,True,Business Development
250,Randy,NaN,1986-02-06,2020-11-26 15:04:00,133943,8.940,True,Sales
251,Sharon,NaN,1990-03-01,2020-11-26 03:46:00,83658,6.513,False,Business Development
252,Ralph,Male,2004-11-11,2020-11-26 01:35:00,71896,4.232,True,Marketing
253,NaN,NaN,2003-04-28,2020-11-26 03:01:00,113732,10.391,True,Sales
254,Edward,Male,1985-05-27,2020-11-26 22:13:00,110485,7.995,False,Client Services
256,Debra,Female,1998-03-13,2020-11-26 23:16:00,48696,4.750,False,Legal
257,NaN,Male,1999-11-25,2020-11-26 06:16:00,42676,15.517,True,Sales
259,Henry,Male,1995-02-06,2020-11-26 08:34:00,89258,15.585,True,Human Resources
261,Marie,Female,1995-08-06,2020-11-26 13:58:00,100308,13.677,False,Product
262,Anne,Female,1986-07-16,2020-11-26 14:08:00,69134,3.723,True,Engineering
263,Sarah,NaN,1985-11-21,2020-11-26 13:08:00,58295,14.603,True,Engineering
264,Stephanie,Female,1983-03-24,2020-11-26 11:15:00,50141,13.218,True,Human Resources
266,NaN,Female,2009-08-05,2020-11-26 08:14:00,115145,14.063,True,Distribution
267,NaN,Male,2005-02-04,2020-11-26 13:01:00,40451,16.044,True,Distribution
268,Irene,Female,1982-03-03,2020-11-26 08:26:00,56526,5.810,True,Finance
269,NaN,Female,1992-08-02,2020-11-26 20:35:00,145316,18.517,True,Human Resources
270,Thomas,Male,2011-04-06,2020-11-26 13:04:00,103235,9.554,True,Human Resources
271,Frank,NaN,2001-11-20,2020-11-26 10:18:00,58563,12.062,True,Marketing
272,Fred,Male,1980-02-20,2020-11-26 02:25:00,74129,18.225,False,Product
273,Nicholas,Male,1994-04-12,2020-11-26 20:21:00,74669,1.113,True,Product
274,Howard,Male,1982-10-05,2020-11-26 07:22:00,97490,5.460,True,Marketing
275,Debra,Female,1994-02-22,2020-11-26 22:25:00,104250,18.456,True,Business Development
276,Christine,Female,1989-07-03,2020-11-26 04:01:00,94345,11.996,False,Finance
277,Brenda,NaN,1991-05-29,2020-11-26 06:32:00,82439,19.062,False,Sales
280,Kevin,Male,1997-07-12,2020-11-26 02:07:00,46080,9.635,False,Business Development
281,Arthur,Male,2014-01-01,2020-11-26 19:46:00,134610,6.147,True,Human Resources
283,Todd,Male,2009-03-11,2020-11-26 03:43:00,107281,1.612,True,Engineering
285,Judy,Female,1997-09-16,2020-11-26 00:10:00,65931,2.304,False,Human Resources
286,Todd,Male,1984-02-02,2020-11-26 10:13:00,69989,10.985,True,Finance
287,Lois,Female,2011-11-09,2020-11-26 07:06:00,147183,9.999,True,Client Services
289,Jessica,Female,1985-09-27,2020-11-26 13:35:00,75145,6.388,True,Legal
290,Jeremy,Male,1988-06-14,2020-11-26 18:20:00,129460,13.657,True,NaN
291,Tammy,Female,1984-11-11,2020-11-26 10:30:00,132839,17.463,True,Client Services
292,Anne,Female,2000-03-07,2020-11-26 06:45:00,44537,18.284,True,Client Services
295,Jesse,Male,1981-03-02,2020-11-26 19:26:00,79582,3.873,False,Legal
296,Jeremy,NaN,1996-11-10,2020-11-26 13:49:00,55394,3.180,True,Sales
297,Daniel,Male,2007-09-15,2020-11-26 22:16:00,123811,7.664,True,Human Resources
298,Patrick,NaN,2004-08-30,2020-11-26 11:43:00,137314,4.542,True,Marketing
299,Emily,Female,1988-01-13,2020-11-26 06:42:00,36711,19.028,True,Human Resources
300,Alan,Male,1988-06-26,2020-11-26 03:54:00,111786,3.592,True,Engineering
302,Adam,Male,2007-07-05,2020-11-26 11:59:00,71276,5.027,True,Human Resources
303,Joan,NaN,1980-07-25,2020-11-26 12:22:00,38712,3.657,False,Client Services
304,Jeremy,Male,1981-08-12,2020-11-26 00:05:00,46930,18.702,True,Finance
305,Margaret,Female,1993-02-06,2020-11-26 13:05:00,125220,3.733,False,Marketing
306,Mark,Male,1984-04-01,2020-11-26 13:21:00,121477,17.440,True,Business Development
307,Marilyn,Female,1981-09-26,2020-11-26 02:23:00,86386,2.937,False,Distribution
308,Cheryl,Female,2009-09-08,2020-11-26 10:16:00,81308,2.196,True,Legal
309,Benjamin,Male,1984-09-11,2020-11-26 06:37:00,84810,15.794,False,Marketing
310,Harold,Male,1990-02-20,2020-11-26 23:00:00,66775,2.158,True,Legal
311,Ernest,NaN,2002-01-18,2020-11-26 01:51:00,72145,13.448,True,Finance
312,Gerald,Male,2001-04-16,2020-11-26 22:09:00,121604,1.923,True,Sales
313,Judy,Female,1991-07-01,2020-11-26 02:33:00,109510,13.457,True,Legal
314,Bobby,Male,1996-03-31,2020-11-26 17:40:00,112117,6.338,False,NaN
315,Bobby,NaN,1995-09-01,2020-11-26 14:09:00,108127,15.858,False,Client Services
319,Jacqueline,Female,1981-11-25,2020-11-26 15:01:00,145988,18.243,False,Marketing
320,NaN,Female,2008-07-08,2020-11-26 23:40:00,62960,14.356,True,Sales
321,Julie,Female,1986-03-23,2020-11-26 09:26:00,56926,7.507,False,Sales
323,Linda,Female,1990-12-16,2020-11-26 02:20:00,115658,3.041,True,Sales
324,Ruby,Female,1988-12-10,2020-11-26 20:27:00,76707,6.031,False,Business Development
326,Jeffrey,Male,1997-06-18,2020-11-26 20:01:00,45150,12.075,True,Product
327,Aaron,Male,1994-01-29,2020-11-26 18:48:00,58755,5.097,True,Marketing

In [10]:
name = df['First Name']=='Robert'
team = df['Team']=='Marketing'
df[name|team]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,1993-08-06,2020-11-26 12:42:00,97308,6.945,True,Marketing
21,Matthew,Male,1995-09-05,2020-11-26 02:12:00,100612,13.645,False,Marketing
26,Craig,Male,2000-02-27,2020-11-26 07:45:00,37598,7.757,True,Marketing
43,Marilyn,Female,1980-12-07,2020-11-26 03:16:00,73524,5.207,True,Marketing
62,NaN,Female,2007-06-12,2020-11-26 17:25:00,58112,19.414,True,Marketing
74,Thomas,Male,1995-06-04,2020-11-26 14:24:00,62096,17.029,False,Marketing
77,Charles,Male,2004-09-14,2020-11-26 20:13:00,107391,1.260,True,Marketing
97,Laura,NaN,2014-07-19,2020-11-26 21:23:00,140371,10.620,True,Marketing
98,Tina,Female,2016-06-16,2020-11-26 19:47:00,100705,16.961,True,Marketing
101,Aaron,Male,2012-02-17,2020-11-26 10:20:00,61602,11.849,True,Marketing
104,John,Male,1989-12-23,2020-11-26 07:01:00,80740,19.305,False,Marketing
112,Willie,Male,2003-11-27,2020-11-26 06:21:00,64363,4.023,False,Marketing
119,Paul,Male,2008-06-03,2020-11-26 15:05:00,41054,12.299,False,Marketing
140,Shirley,Female,1981-02-28,2020-11-26 13:23:00,113850,1.854,False,Marketing
150,Sean,Male,1996-05-04,2020-11-26 20:59:00,135490,19.934,False,Marketing
158,Norma,Female,1999-02-28,2020-11-26 20:45:00,114412,8.756,True,Marketing
159,James,NaN,1983-11-22,2020-11-26 22:52:00,68501,14.316,False,Marketing
168,Peter,NaN,1987-09-03,2020-11-26 17:59:00,38989,7.017,True,Marketing
187,Roger,Male,2004-11-19,2020-11-26 15:55:00,51430,6.460,False,Marketing
201,Kimberly,Female,1997-07-15,2020-11-26 05:57:00,36643,7.953,False,Marketing
204,Willie,Male,2006-06-06,2020-11-26 09:45:00,55281,4.935,True,Marketing
216,Matthew,Male,2013-07-31,2020-11-26 08:04:00,142373,2.462,False,Marketing
220,NaN,Female,1991-06-17,2020-11-26 12:49:00,71945,5.560,True,Marketing
242,Robert,Male,1990-10-27,2020-11-26 19:15:00,38041,18.428,True,Engineering
252,Ralph,Male,2004-11-11,2020-11-26 01:35:00,71896,4.232,True,Marketing
271,Frank,NaN,2001-11-20,2020-11-26 10:18:00,58563,12.062,True,Marketing
274,Howard,Male,1982-10-05,2020-11-26 07:22:00,97490,5.460,True,Marketing
293,Jesse,Male,1999-10-25,2020-11-26 15:35:00,118733,9.653,False,Marketing
298,Patrick,NaN,2004-08-30,2020-11-26 11:43:00,137314,4.542,True,Marketing
305,Margaret,Female,1993-02-06,2020-11-26 13:05:00,125220,3.733,False,Marketing
309,Benjamin,Male,1984-09-11,2020-11-26 06:37:00,84810,15.794,False,Marketing
319,Jacqueline,Female,1981-11-25,2020-11-26 15:01:00,145988,18.243,False,Marketing
327,Aaron,Male,1994-01-29,2020-11-26 18:48:00,58755,5.097,True,Marketing
331,Evelyn,Female,1983-09-03,2020-11-26 13:58:00,36759,17.269,True,Marketing
335,Robert,Male,2014-11-18,2020-11-26 05:00:00,85799,19.930,False,Finance
353,NaN,Male,1997-04-22,2020-11-26 21:36:00,65078,3.095,True,Marketing
379,NaN,Female,2002-09-18,2020-11-26 12:39:00,118906,4.537,True,Marketing
387,Robert,Male,1994-10-29,2020-11-26 04:26:00,123294,19.894,False,Client Services
400,Billy,NaN,2004-03-16,2020-11-26 08:21:00,62913,18.241,True,Marketing
403,Craig,Male,1984-02-08,2020-11-26 04:45:00,113506,19.642,False,Marketing
413,Johnny,Male,1992-09-14,2020-11-26 08:21:00,115194,5.861,True,Marketing
446,Cheryl,Female,1994-08-16,2020-11-26 08:33:00,67150,15.850,True,Marketing
451,Terry,NaN,2016-07-15,2020-11-26 00:29:00,140002,19.490,True,Marketing
452,Scott,Male,2012-11-17,2020-11-26 14:47:00,146812,1.965,True,Marketing
454,NaN,Male,1995-02-21,2020-11-26 00:26:00,136602,10.429,True,Marketing
459,Charles,NaN,1987-03-01,2020-11-26 13:00:00,137171,5.574,True,Marketing
461,Jeremy,Male,2001-08-09,2020-11-26 03:56:00,43354,13.946,False,Marketing
464,Lawrence,Male,2005-05-13,2020-11-26 01:25:00,74640,18.641,False,Marketing
468,Janice,Female,1997-06-28,2020-11-26 13:48:00,136032,10.696,True,Marketing
484,Joe,Male,2000-04-14,2020-11-26 15:14:00,50645,11.119,False,Marketing
488,Robert,Male,2007-03-11,2020-11-26 11:20:00,135882,19.944,False,Legal
490,Judith,Female,2007-11-23,2020-11-26 13:22:00,117055,7.461,False,Marketing
496,Johnny,Male,2016-02-26,2020-11-26 19:39:00,76394,5.437,True,Marketing
503,Roger,Male,2015-08-03,2020-11-26 16:56:00,125033,4.887,True,Marketing
531,Virginia,Female,2010-05-02,2020-11-26 21:10:00,123649,10.154,True,Marketing
535,Louise,Female,1981-09-18,2020-11-26 05:47:00,91462,8.205,False,Marketing
544,Roger,Male,2010-07-03,2020-11-26 17:11:00,105689,13.320,True,Marketing
550,Gregory,Male,1984-06-18,2020-11-26 03:46:00,82726,16.304,True,Marketing
556,Arthur,Male,2014-12-16,2020-11-26 16:56:00,66819,6.639,True,Marketing
568,Susan,Female,1986-04-18,2020-11-26 09:31:00,90829,19.142,False,Marketing
571,Jonathan,Male,1995-04-06,2020-11-26 22:38:00,56993,18.623,False,Marketing
581,Ernest,Male,1990-01-28,2020-11-26 00:08:00,81919,15.118,False,Marketing
585,Shirley,Female,1988-04-16,2020-11-26 11:09:00,132156,2.754,False,Marketing
586,Rose,Female,2004-10-30,2020-11-26 16:34:00,56961,7.585,False,Marketing
601,Christine,NaN,1980-06-15,2020-11-26 18:00:00,50366,9.862,True,Marketing
611,Elizabeth,NaN,1981-02-16,2020-11-26 03:58:00,52730,12.525,False,Marketing
617,Kathy,Female,2001-01-14,2020-11-26 05:11:00,45682,1.451,True,Marketing
625,Cynthia,Female,2015-06-29,2020-11-26 06:38:00,82408,8.701,True,Marketing
627,Anne,Female,1984-11-21,2020-11-26 12:30:00,128305,16.636,False,Marketing
629,Debra,Female,1983-03-12,2020-11-26 12:19:00,74911,19.513,False,Marketing
645,Anna,NaN,1985-03-13,2020-11-26 09:19:00,45418,10.162,False,Marketing
656,Lisa,Female,1982-02-09,2020-11-26 18:44:00,113592,17.108,True,Marketing
659,Steve,NaN,2009-08-27,2020-11-26 15:41:00,53692,4.785,True,Marketing
667,Douglas,NaN,2009-02-04,2020-11-26 02:03:00,104496,14.771,True,Marketing
672,Robert,Male,1982-11-05,2020-11-26 12:41:00,111580,10.982,False,Human Resources
675,Diane,Female,2009-10-30,2020-11-26 18:56:00,130577,12.791,False,Marketing
676,Annie,Female,1992-06-06,2020-11-26 10:04:00,138925,9.801,True,Marketing
696,Samuel,Male,2012-05-25,2020-11-26 16:40:00,85550,11.593,True,Marketing
722,Joshua,Male,1997-06-27,2020-11-26 15:23:00,95003,5.197,True,Marketing
730,Nicole,Female,2009-04-26,2020-11-26 00:40:00,66047,18.674,True,Marketing
740,Russell,NaN,2009-05-09,2020-11-26 11:59:00,149456,3.533,False,Marketing
769,Samuel,NaN,2002-10-07,2020-11-26 03:08:00,141305,9.849,True,Marketing
785,NaN,Female,1982-07-24,2020-11-26 00:00:00,57811,8.941,True,Marketing
798,Lawrence,Male,1984-10-01,2020-11-26 14:06:00,102589,17.952,True,Marketing
811,Judith,Female,1989-09-03,2020-11-26 11:16:00,134048,6.818,True,Marketing
813,Evelyn,Female,2002-02-10,2020-11-26 04:44:00,123621,19.767,True,Marketing
817,Ruby,Female,2008-05-31,2020-11-26 20:41:00,83112,4.083,False,Marketing
824,Julia,Female,2014-08-18,2020-11-26 03:12:00,97566,2.147,False,Marketing
825,Robert,NaN,2000-12-04,2020-11-26 01:20:00,69267,5.890,True,Sales
860,Phillip,Male,1984-10-07,2020-11-26 11:05:00,36837,14.660,False,Marketing
867,Earl,Male,2013-06-15,2020-11-26 03:00:00,48046,7.737,False,Marketing
870,Cynthia,NaN,1996-11-19,2020-11-26 22:40:00,107816,18.751,False,Marketing
876,Terry,NaN,1992-09-11,2020-11-26 16:41:00,41238,8.219,False,Marketing
880,Robert,NaN,2007-05-25,2020-11-26 03:17:00,90998,8.382,False,Finance
881,Ruby,Female,1980-01-28,2020-11-26 23:08:00,142868,6.318,False,Marketing
883,Kathryn,Female,1995-10-27,2020-11-26 15:39:00,57300,18.015,False,Marketing
894,Betty,Female,2002-11-19,2020-11-26 10:40:00,37005,7.645,True,Marketing
899,Walter,Male,1992-05-21,2020-11-26 00:39:00,144701,16.323,True,Marketing
913,Lois,Female,2015-12-11,2020-11-26 16:10:00,99747,6.168,False,Marketing
930,Nancy,Female,2001-09-10,2020-11-26 23:57:00,85213,2.386,True,Marketing
942,Lori,Female,2015-11-20,2020-11-26 13:15:00,75498,6.537,True,Marketing
947,NaN,Male,2012-07-30,2020-11-26 15:07:00,107351,5.329,True,Marketing
986,Donna,Female,1982-11-26,2020-11-26 07:04:00,82871,17.999,False,Marketing
991,Rose,Female,2002-08-25,2020-11-26 05:12:00,134505,11.051,True,Marketing
994,George,Male,2013-06-21,2020-11-26 17:47:00,98874,4.479,True,Marketing