# A Review of the .apply() Method in single column

In [1]:
import pandas as pd

In [2]:
%%HTML
<style>
    table.dataframe th,table.dataframe td
        {
            background-color:white!important;
            color:black;
            border:1px solid black
        }
</style>

In [4]:
bond = pd.read_csv('../jamesbond.csv',index_col='Film')
bond.sort_index(inplace=True)
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [7]:
def add_million(n):
    return str(n)+' M'
bond['Box Office'] = bond['Box Office'].apply(add_million)

In [8]:
bond['Budget'] = bond['Budget'].apply(add_million)

In [9]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2 M,54.5 M,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5 M,145.3 M,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0 M,85.0 M,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5 M,34.7 M,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4 M,154.2 M,17.9
Dr. No,1962,Sean Connery,Terence Young,448.8 M,7.0 M,0.6
For Your Eyes Only,1981,Roger Moore,John Glen,449.4 M,60.2 M,NaN
From Russia with Love,1963,Sean Connery,Terence Young,543.8 M,12.6 M,1.6
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5 M,76.9 M,5.1
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4 M,18.6 M,3.2
Licence to Kill,1989,Timothy Dalton,John Glen,250.9 M,56.7 M,7.9
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3 M,30.8 M,NaN
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0 M,91.5 M,NaN
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0 M,86.0 M,NaN
Octopussy,1983,Roger Moore,John Glen,373.8 M,53.9 M,7.8
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5 M,37.3 M,0.6
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2 M,181.4 M,8.1
Skyfall,2012,Daniel Craig,Sam Mendes,943.5 M,170.2 M,14.5
Spectre,2015,Daniel Craig,Sam Mendes,726.7 M,206.3 M,NaN
The Living Daylights,1987,Timothy Dalton,John Glen,313.5 M,68.8 M,5.2
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0 M,27.7 M,NaN
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0 M,45.1 M,NaN
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5 M,158.3 M,13.5
Thunderball,1965,Sean Connery,Terence Young,848.1 M,41.9 M,4.7
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2 M,133.9 M,10.0
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2 M,59.9 M,4.4

In [22]:
def add_million(n):
    if(n):
        return str(n)+' K'

In [23]:
bond = pd.read_csv('../jamesbond.csv',index_col='Film')
bond.sort_index(inplace=True)
bond.head()

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2,54.5,9.1
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5,145.3,3.3
Casino Royale,1967,David Niven,Ken Hughes,315.0,85.0,NaN
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5,34.7,5.8
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4,154.2,17.9

In [24]:
columns=['Box Office','Bond Actor Salary','Budget']
for col in columns:
    bond[col] = bond[col].apply(add_million)

In [26]:
bond

,Year,Actor,Director,Box Office,Budget,Bond Actor Salary
Film,,,,,,
A View to a Kill,1985,Roger Moore,John Glen,275.2 K,54.5 K,9.1 K
Casino Royale,2006,Daniel Craig,Martin Campbell,581.5 K,145.3 K,3.3 K
Casino Royale,1967,David Niven,Ken Hughes,315.0 K,85.0 K,nan K
Diamonds Are Forever,1971,Sean Connery,Guy Hamilton,442.5 K,34.7 K,5.8 K
Die Another Day,2002,Pierce Brosnan,Lee Tamahori,465.4 K,154.2 K,17.9 K
Dr. No,1962,Sean Connery,Terence Young,448.8 K,7.0 K,0.6 K
For Your Eyes Only,1981,Roger Moore,John Glen,449.4 K,60.2 K,nan K
From Russia with Love,1963,Sean Connery,Terence Young,543.8 K,12.6 K,1.6 K
GoldenEye,1995,Pierce Brosnan,Martin Campbell,518.5 K,76.9 K,5.1 K
Goldfinger,1964,Sean Connery,Guy Hamilton,820.4 K,18.6 K,3.2 K
Licence to Kill,1989,Timothy Dalton,John Glen,250.9 K,56.7 K,7.9 K
Live and Let Die,1973,Roger Moore,Guy Hamilton,460.3 K,30.8 K,nan K
Moonraker,1979,Roger Moore,Lewis Gilbert,535.0 K,91.5 K,nan K
Never Say Never Again,1983,Sean Connery,Irvin Kershner,380.0 K,86.0 K,nan K
Octopussy,1983,Roger Moore,John Glen,373.8 K,53.9 K,7.8 K
On Her Majesty's Secret Service,1969,George Lazenby,Peter R. Hunt,291.5 K,37.3 K,0.6 K
Quantum of Solace,2008,Daniel Craig,Marc Forster,514.2 K,181.4 K,8.1 K
Skyfall,2012,Daniel Craig,Sam Mendes,943.5 K,170.2 K,14.5 K
Spectre,2015,Daniel Craig,Sam Mendes,726.7 K,206.3 K,nan K
The Living Daylights,1987,Timothy Dalton,John Glen,313.5 K,68.8 K,5.2 K
The Man with the Golden Gun,1974,Roger Moore,Guy Hamilton,334.0 K,27.7 K,nan K
The Spy Who Loved Me,1977,Roger Moore,Lewis Gilbert,533.0 K,45.1 K,nan K
The World Is Not Enough,1999,Pierce Brosnan,Michael Apted,439.5 K,158.3 K,13.5 K
Thunderball,1965,Sean Connery,Terence Young,848.1 K,41.9 K,4.7 K
Tomorrow Never Dies,1997,Pierce Brosnan,Roger Spottiswoode,463.2 K,133.9 K,10.0 K
You Only Live Twice,1967,Sean Connery,Lewis Gilbert,514.2 K,59.9 K,4.4 K